export const SET_AUTH_DATA = 'SET_AUTH_DATA'

export const LOGIN_GOOGLE_REQUEST = 'LOGIN_GOOGLE_REQUEST'
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS'
export const LOGIN_GOOGLE_FAILURE = 'LOGIN_GOOGLE_FAILURE'

export const LOGOUT = 'LOGOUT'
