export const GET_LANGUAGES_REQUEST = 'GET_LANGUAGES_REQUEST'
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS'
export const GET_LANGUAGES_FAILURE = 'GET_LANGUAGES_FAILURE'

export const GET_TRANSLATION_REQUEST = 'GET_TRANSLATION_REQUEST'
export const GET_TRANSLATION_SUCCESS = 'GET_TRANSLATION_SUCCESS'
export const GET_TRANSLATION_FAILURE = 'GET_TRANSLATION_FAILURE'
